In [1]:
#Dependencies
import pandas as pd
import requests
import json
import os

#Datasets
#Census Data 
BnB = "AB_2019.csv"
#Policy Data
NY = "December_Census.csv"

In [2]:
#Creating the dataframes from the datasets...
BnB_df = pd.read_csv(BnB)
NY_df = pd.read_csv(NY)

In [3]:
#Removing excess variables...
BnB_DF = BnB_df[['neighbourhood_group', 'room_type', 'price', 'minimum_nights', 'reviews_per_month']]
NY_DF = NY_df.drop(labels=range(17, 85), axis=0)

In [4]:
BnB_DF

,neighbourhood_group,room_type,price,minimum_nights,reviews_per_month
0,Brooklyn,Private room,149,1,0.21
1,Manhattan,Entire home/apt,225,1,0.38
2,Manhattan,Private room,150,3,NaN
3,Brooklyn,Entire home/apt,89,1,4.64
4,Manhattan,Entire home/apt,80,10,0.10
...,...,...,...,...,...
48890,Brooklyn,Private room,70,2,NaN
48891,Brooklyn,Private room,40,4,NaN
48892,Manhattan,Entire home/apt,115,10,NaN
48893,Manhattan,Shared room,55,1,NaN
48894,Manhattan,Private room,90,7,NaN

In [5]:
NY_DF

,Fact,Fact Note,"Queens County, New York","Value Note for Queens County, New York","Richmond County, New York","Value Note for Richmond County, New York","New York County, New York","Value Note for New York County, New York","Kings County, New York","Value Note for Kings County, New York","Bronx County, New York","Value Note for Bronx County, New York"
0,"Population Estimates, July 1 2021, (V2021)",NaN,"2,331,143",NaN,"493,494",NaN,"1,576,876",NaN,"2,641,052",NaN,"1,424,948",NaN
1,"Population estimates base, April 1, 2020, (V2021)",NaN,"2,405,464",NaN,"495,747",NaN,"1,694,251",NaN,"2,736,074",NaN,"1,472,654",NaN
2,"Population, percent change - April 1, 2020 (es...",NaN,-3.10%,NaN,-0.50%,NaN,-6.90%,NaN,-3.50%,NaN,-3.20%,NaN
3,"Population, Census, April 1, 2020",NaN,"2,405,464",NaN,"495,747",NaN,"1,694,251",NaN,"2,736,074",NaN,"1,472,654",NaN
4,"Population, Census, April 1, 2010",NaN,"2,230,722",NaN,"468,730",NaN,"1,585,873",NaN,"2,504,700",NaN,"1,385,108",NaN
5,"Persons under 5 years, percent",NaN,5.70%,NaN,5.50%,NaN,4.40%,NaN,6.70%,NaN,6.70%,NaN
6,"Persons under 18 years, percent",NaN,20.00%,NaN,21.70%,NaN,14.70%,NaN,22.70%,NaN,24.50%,NaN
7,"Persons 65 years and over, percent",NaN,17.40%,NaN,17.00%,NaN,18.30%,NaN,15.10%,NaN,14.00%,NaN
8,"Female persons, percent",NaN,51.10%,NaN,51.10%,NaN,52.40%,NaN,52.40%,NaN,52.60%,NaN
9,"White alone, percent",NaN,47.30%,NaN,73.00%,NaN,63.50%,NaN,49.90%,NaN,44.30%,NaN
10,"Black or African American alone, percent",(a),20.70%,NaN,11.60%,NaN,18.50%,NaN,33.30%,NaN,43.80%,NaN
11,"American Indian and Alaska Native alone, percent",(a),1.40%,NaN,0.70%,NaN,1.30%,NaN,1.00%,NaN,3.10%,NaN
12,"Asian alone, percent",(a),27.30%,NaN,12.30%,NaN,13.00%,NaN,12.90%,NaN,4.70%,NaN
13,Native Hawaiian and Other Pacific Islander alo...,(a),0.20%,NaN,0.10%,NaN,0.20%,NaN,0.10%,NaN,0.40%,NaN
14,"Two or More Races, percent",NaN,3.10%,NaN,2.30%,NaN,3.60%,NaN,2.80%,NaN,3.80%,NaN
15,"Hispanic or Latino, percent",(b),28.10%,NaN,18.70%,NaN,26.40%,NaN,18.80%,NaN,56.40%,NaN
16,"White alone, not Hispanic or Latino, percent",NaN,24.50%,NaN,58.30%,NaN,45.80%,NaN,37.00%,NaN,9.00%,NaN

In [6]:
DF_NY = NY_DF[["Fact","Queens County, New York", "Richmond County, New York","New York County, New York" ,"Kings County, New York","Bronx County, New York"]]

In [7]:
DF_NY

,Fact,"Queens County, New York","Richmond County, New York","New York County, New York","Kings County, New York","Bronx County, New York"
0,"Population Estimates, July 1 2021, (V2021)","2,331,143","493,494","1,576,876","2,641,052","1,424,948"
1,"Population estimates base, April 1, 2020, (V2021)","2,405,464","495,747","1,694,251","2,736,074","1,472,654"
2,"Population, percent change - April 1, 2020 (es...",-3.10%,-0.50%,-6.90%,-3.50%,-3.20%
3,"Population, Census, April 1, 2020","2,405,464","495,747","1,694,251","2,736,074","1,472,654"
4,"Population, Census, April 1, 2010","2,230,722","468,730","1,585,873","2,504,700","1,385,108"
5,"Persons under 5 years, percent",5.70%,5.50%,4.40%,6.70%,6.70%
6,"Persons under 18 years, percent",20.00%,21.70%,14.70%,22.70%,24.50%
7,"Persons 65 years and over, percent",17.40%,17.00%,18.30%,15.10%,14.00%
8,"Female persons, percent",51.10%,51.10%,52.40%,52.40%,52.60%
9,"White alone, percent",47.30%,73.00%,63.50%,49.90%,44.30%
10,"Black or African American alone, percent",20.70%,11.60%,18.50%,33.30%,43.80%
11,"American Indian and Alaska Native alone, percent",1.40%,0.70%,1.30%,1.00%,3.10%
12,"Asian alone, percent",27.30%,12.30%,13.00%,12.90%,4.70%
13,Native Hawaiian and Other Pacific Islander alo...,0.20%,0.10%,0.20%,0.10%,0.40%
14,"Two or More Races, percent",3.10%,2.30%,3.60%,2.80%,3.80%
15,"Hispanic or Latino, percent",28.10%,18.70%,26.40%,18.80%,56.40%
16,"White alone, not Hispanic or Latino, percent",24.50%,58.30%,45.80%,37.00%,9.00%

In [8]:
#Exporting new csv files 
BnB_df.to_csv("BnB_df.csv", index=False, header=True)
DF_NY.to_csv("DF_NY.csv", index=False, header=True)

In [9]:
#Connecting to SQL 
from sqlalchemy import create_engine